services:

  postgres:
    image: postgres:16-alpine
    container_name: postgres-form
    environment:
      POSTGRES_DB: formulaire_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./apk-formulaire
    container_name: backend
    ports:
      - "8080:8080"
    environment:
      # Override application.yaml : utilise le service "postgres" du compose (pas localhost)
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/formulaire_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    depends_on:
      postgres:
        condition: service_healthy

  frontend:
    build: ./formulaire-ui/frontend
    container_name: frontend
    ports:
      - "4200:80"
    depends_on:
      - backend

volumes:
  postgres_data: